ServiceRequestError: No connection adapters were found for '2990RWVY4a5zIPUV5MkI56hVSVoQMhEQQk8jvbt8pPX3BQ1RU8zTJQQJ99ALACYeBjFXJ3w3AAALACOGTRR5/formrecognizer/documentModels/prebuilt-layout:analyze?stringIndexType=unicodeCodePoint&api-version=2023-07-31'
Traceback:
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/main.py", line 60, in <module>
    poller = document_analysis_client.begin_analyze_document(
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
    return func(*args, **kwargs)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/ai/formrecognizer/_document_analysis_client.py", line 129, in begin_analyze_document
    return _client_op_path.begin_analyze_document(  # type: ignore
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 105, in wrapper_use_tracer
    return func(*args, **kwargs)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/ai/formrecognizer/_generated/v2023_07_31/operations/_document_models_operations.py", line 518, in begin_analyze_document
    raw_result = self._analyze_document_initial(  # type: ignore
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/ai/formrecognizer/_generated/v2023_07_31/operations/_document_models_operations.py", line 434, in _analyze_document_initial
    pipeline_response = self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 240, in run
    return first_node.send(pipeline_request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
[Previous line repeated 2 more times]
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 204, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 573, in send
    raise err
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 551, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 96, in send
    response = self.next.send(request)
[Previous line repeated 4 more times]
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 128, in send
    self._sender.send(request.http_request, **request.context.options),
File "/home/runner/Azure-DI-langchaincommunity-documentloaders/.pythonlibs/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 409, in send
    raise error